project:
  type: website
  output-dir: _site

website:
  title: "Intro to omics with R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r_tidyverse_workshop.qmd
        text: R Tidyverse
      - href: rnaseq_workshop.qmd
        text: RNA-seq
